### ISSUE TITLE
Calculation of change direction

### ISSUE THREAD

**Issue by TobiasBg** [midudev/covid-19-spread-simulator#6]
Hi,

not really an issue, but more a question:

What's the method/idea/math behind the calculation of the change direction in lines https://github.com/midudev/covid-19-spread-simulator/blob/94f09bdcbab341e753311028d6a4e7bc3f734e74/src/Ball.js#L56-L61 ?

I'm a bit confused as to why the velocity of the otherBall apparently doesn't play a role?

Thanks!
Tobias

**Comment by TobiasBg** [comment]
Hi again,

to clarify: I'm just curious why this simple calculation works, when all other sources for ball collisions on the web seem to be using more complex formulas, with rotations of vectors, conservation of momentum, etc.
Can you maybe explain how it's derived? Thanks a lot!

Best wishes,
Tobias

**Comment by BaconBoi95** [comment]
well, this is just a little bit of code, the balls have a static speed level set when they are constructed, meaning it's just some collision code and checking the velocity just for calculating what goes where, I just work on flexibility so I don't know
